
load:
	javac -cp :couchbase-client-1.1-dp2.jar:couchbase-client-1.1-dp2-javadocs.jar:spymemcached-2.8.4.jar:spymemcached-2.8.4-javadocs.jar:commons-codec-1.5.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar LoadTask.java

	java -cp .:couchbase-client-1.1-dp2.jar:couchbase-client-1.1-dp2-javadocs.jar:spymemcached-2.8.4.jar:spymemcached-2.8.4-javadocs.jar:commons-codec-1.5.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar LoadTask

observe:
        javac -cp :couchbase-client-1.1-dp2.jar:couchbase-client-1.1-dp2-javadocs.jar:spymemcached-2.8.4.jar:spymemcached-2.8.4-javadocs.jar:commons-codec-1.5.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar LoadTaskWithObserve.java

        java -cp .:couchbase-client-1.1-dp2.jar:couchbase-client-1.1-dp2-javadocs.jar:spymemcached-2.8.4.jar:spymemcached-2.8.4-javadocs.jar:commons-codec-1.5.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar LoadTaskWithObserve

view:
	javac -cp :couchbase-client-1.1-dp2.jar:couchbase-client-1.1-dp2-javadocs.jar:spymemcached-2.8.4.jar:spymemcached-2.8.4-javadocs.jar:commons-codec-1.5.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar ViewQuery.java

	java -cp .:couchbase-client-1.1-dp2.jar:couchbase-client-1.1-dp2-javadocs.jar:spymemcached-2.8.4.jar:spymemcached-2.8.4-javadocs.jar:commons-codec-1.5.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar ViewQuery

clean:
	rm -f *.class
