compile:
	javac -cp :couchbase-client-1.1.6.jar:jettison-1.1.jar:spymemcached-2.8.12.jar:commons-codec-1.5.jar:couchbase-client-meta-1.0-SNAPSHOT.jar:netty-3.5.5.Final.jar:couchbase-client-1.1.6-javadoc.jar:httpcore-4.1.1.jar:spymemcached-2.8.12-javadocs.jar:couchbase-client-1.1.6-sources.jar:httpcore-nio-4.1.1.jar:spymemcached-2.8.12-sources.jar Helper.java

run:
	java -cp .:couchbase-client-1.1.6.jar:jettison-1.1.jar:spymemcached-2.8.12.jar:commons-codec-1.5.jar:couchbase-client-meta-1.0-SNAPSHOT.jar:netty-3.5.5.Final.jar:couchbase-client-1.1.6-javadoc.jar:httpcore-4.1.1.jar:spymemcached-2.8.12-javadocs.jar:couchbase-client-1.1.6-sources.jar:httpcore-nio-4.1.1.jar:spymemcached-2.8.12-sources.jar Helper

clean:
	rm -rf *.class
