Mainhelper:
	javac -cp :couchbase-client-1.1.2c-TEST.jar:couchbase-client-1.1.2c-TEST-javadocs.jar:couchbase-client-1.1.2c-TEST-sources.jar:spymemcached-2.8.6-SNAPSHOT.jar:spymemcached-2.8.6-SNAPSHOT-javadocs.jar:spymemcached-2.8.6-SNAPSHOT-sources.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar:commons-codec-1.5.jar Mainhelper.java 

ViewQuery:
	javac -cp :couchbase-client-1.1.2c-TEST.jar:couchbase-client-1.1.2c-TEST-javadocs.jar:couchbase-client-1.1.2c-TEST-sources.jar:spymemcached-2.8.6-SNAPSHOT.jar:spymemcached-2.8.6-SNAPSHOT-javadocs.jar:spymemcached-2.8.6-SNAPSHOT-sources.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar:commons-codec-1.5.jar ViewQuery.java

clean:
	rm -rf *.class
