Loadrunner:
	javac -cp :asm-3.3.1.jar:cglib-2.2.2.jar:commons-codec-1.5.jar:couchbase-client-1.1.3-javadocs.jar:couchbase-client-1.1.3-sources.jar:couchbase-client-1.1.3.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.5.5.Final.jar:spymemcached-2.8.12-javadocs.jar:spymemcached-2.8.12-sources.jar:spymemcached-2.8.12.jar:spymemcached-test-2.8.12.jar Loadrunner.java 

RunLoadrunner:
	java -cp .:asm-3.3.1.jar:cglib-2.2.2.jar:commons-codec-1.5.jar:couchbase-client-1.1.3-javadocs.jar:couchbase-client-1.1.3-sources.jar:couchbase-client-1.1.3.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.5.5.Final.jar:spymemcached-2.8.12-javadocs.jar:spymemcached-2.8.12-sources.jar:spymemcached-2.8.12.jar:spymemcached-test-2.8.12.jar Loadrunner

clean:
	rm -rf *.class
