calculate:
	g++ theCalc.cc -o theCalc && ./theCalc $(TESTARGS) && rm -f theCalc

estimate:
	g++ theFilter.cc -o theFilter && ./theFilter $(TESTARGS) && rm -f theFilter

clean:
	rm -f theCalc theFilter
