mix:
	javac -cp :commons-codec-1.5.jar:couchbase-client-1.1.4-javadocs.jar:couchbase-client-1.1.4-sources.jar:couchbase-client-1.1.4.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.5.5.Final.jar:spymemcached-2.8.12-javadocs.jar:spymemcached-2.8.12-sources.jar:spymemcached-2.8.12.jar Mixer.java

runmix:
	java -cp .:commons-codec-1.5.jar:couchbase-client-1.1.4-javadocs.jar:couchbase-client-1.1.4-sources.jar:couchbase-client-1.1.4.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.5.5.Final.jar:spymemcached-2.8.12-javadocs.jar:spymemcached-2.8.12-sources.jar:spymemcached-2.8.12.jar Mixer

esc:
	javac -cp :commons-codec-1.5.jar:couchbase-client-1.1.4-javadocs.jar:couchbase-client-1.1.4-sources.jar:couchbase-client-1.1.4.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.5.5.Final.jar:spymemcached-2.8.12-javadocs.jar:spymemcached-2.8.12-sources.jar:spymemcached-2.8.12.jar Escalated.java

runesc:
	java -cp .:commons-codec-1.5.jar:couchbase-client-1.1.4-javadocs.jar:couchbase-client-1.1.4-sources.jar:couchbase-client-1.1.4.jar:httpcore-4.1.1.jar:httpcore-nio-4.1.1.jar:jettison-1.1.jar:netty-3.5.5.Final.jar:spymemcached-2.8.12-javadocs.jar:spymemcached-2.8.12-sources.jar:spymemcached-2.8.12.jar Escalated

clean:
	rm -rf *.class
