
load:
	javac -cp :couchbase-client-1.1.0c-RC.jar:couchbase-client-1.1.0c-RC-javadocs.jar:couchbase-client-1.1.0c-RC-sources.jar:spymemcached-2.8.3.jar:spymemcached-2.8.3-javadocs.jar:spymemcached-2.8.3-sources.jar:commons-codec-1.5.jar:httpcore-4.2.1.jar:httpcore-nio-4.1.1.jar:httpclient-cache-4.2.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar LoadTask.java

	java -cp .:couchbase-client-1.1.0c-RC.jar:couchbase-client-1.1.0c-RC-javadocs.jar:couchbase-client-1.1.0c-RC-sources.jar:spymemcached-2.8.3.jar:spymemcached-2.8.3-javadocs.jar:spymemcached-2.8.3-sources.jar:commons-codec-1.5.jar:httpcore-4.2.1.jar:httpcore-nio-4.1.1.jar:httpclient-cache-4.2.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar LoadTask

view:
	javac -cp :couchbase-client-1.1.0c-RC.jar:couchbase-client-1.1.0c-RC-javadocs.jar:couchbase-client-1.1.0c-RC-sources.jar:spymemcached-2.8.3.jar:spymemcached-2.8.3-javadocs.jar:spymemcached-2.8.3-sources.jar:commons-codec-1.5.jar:httpcore-4.2.1.jar:httpcore-nio-4.1.1.jar:httpclient-cache-4.2.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar ViewQuery.java

	java -cp .:couchbase-client-1.1.0c-RC.jar:couchbase-client-1.1.0c-RC-javadocs.jar:couchbase-client-1.1.0c-RC-sources.jar:spymemcached-2.8.3.jar:spymemcached-2.8.3-javadocs.jar:spymemcached-2.8.3-sources.jar:commons-codec-1.5.jar:httpcore-4.2.1.jar:httpcore-nio-4.1.1.jar:httpclient-cache-4.2.1.jar:jettison-1.1.jar:netty-3.2.0.Final.jar ViewQuery

clean:
	rm -rf *.class
